.TH hsh Simple Shell 1
.SH NAME
hsh Simple Shell \- A Simple functional shell emulation in C  
.SH SYNOPSIS
.B hsh
[ h ]
[ b ]
.SH DESCRIPTION
.B hsh Simple Shell
This is a Simple Shell that can take arguements, process commands and store data like other *nix shells.
It is based on UBUNTU 20.04 os.
.SH OPTIONS
.TP
.BR h
Print help/ man page(this page) 
.TP
.BR b 
Print bonus commands
.SH AUTHOR
Francis Amenya © 2024 
